import React, { useContext ,useState} from 'react'
import { getSession, useSession } from 'next-auth/react'
import Login from '../components/Login'
import { LeftSideBar } from '@/components/LeftSideBar'
import Head from 'next/head'

import Singlepost from '../components/Singlepost'
import Comment from "../components/Comment"
import { useRouter } from 'next/router'
import { AppContext } from '@/context/AppContext'
import Modal from '../components/Modal'

export const PostPage = () => {
    const [cont, setcont] = useState({});
const changes =(value)=>{
  console.log("yes")
  setcont(value)
  
}

  const { data: session } = useSession()
 
  if (!session) return <Login />

  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='relative max-w-[1400px] mx-auto'>
        <LeftSideBar />
        <div className='flex gap-6'>
          <Singlepost />
          {cont?.isModalOpen && <Modal  appContext={cont} setAppcontext={setcont} setcont={changes} />}
        </div>
      </main>

    </div>
  )
}

export default PostPage

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session
    },
  };
}